# Generated by Django 3.0.5 on 2020-05-01 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabs', '0005_auto_20200501_2132'),
    ]

    operations = [
        migrations.AddField(
            model_name='guitar',
            name='url',
            field=models.SlugField(default='1', max_length=100),
        ),
    ]
