# Generated by Django 3.0.5 on 2020-05-01 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tabs', '0006_guitar_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guitar',
            name='url',
        ),
    ]
