# Generated by Django 3.0.5 on 2020-05-01 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabs', '0008_guitar_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guitar',
            name='url',
            field=models.SlugField(max_length=100),
        ),
    ]
