# Generated by Django 3.0.5 on 2020-05-01 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabs', '0009_auto_20200502_0000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guitar',
            name='manufacturer',
        ),
        migrations.AddField(
            model_name='guitar',
            name='manufacturers',
            field=models.ManyToManyField(to='tabs.Manufacturer', verbose_name='Manufacturers'),
        ),
    ]
