# Generated by Django 3.0.5 on 2020-05-01 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabs', '0011_auto_20200502_0135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='tab',
            field=models.CharField(default='songsterr.com', max_length=100, verbose_name='Tab'),
        ),
    ]
