# Generated by Django 3.0.5 on 2020-05-01 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabs', '0012_auto_20200502_0140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='url',
            field=models.SlugField(max_length=100),
        ),
        migrations.AlterField(
            model_name='guitarist',
            name='url',
            field=models.SlugField(max_length=100),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='url',
            field=models.SlugField(max_length=100),
        ),
        migrations.AlterField(
            model_name='song',
            name='url',
            field=models.SlugField(max_length=100),
        ),
    ]
