# Generated by Django 3.0.5 on 2020-05-01 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabs', '0013_auto_20200502_0142'),
    ]

    operations = [
        migrations.AddField(
            model_name='guitar',
            name='genres',
            field=models.ManyToManyField(to='tabs.Genre', verbose_name='Genres'),
        ),
    ]
